# Generated by Django 5.0.2 on 2024-02-25 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
