# Generated by Django 5.0.2 on 2024-03-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='header_logo',
            field=models.ImageField(default='company/default_header.', upload_to='company'),
        ),
    ]
