# Generated by Django 5.0.2 on 2024-03-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_header_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='header_logo',
            field=models.ImageField(default='defaults/default_header.png', upload_to='company'),
        ),
    ]
