# Generated by Django 5.0.2 on 2024-03-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_company_header_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('can_update_settings', 'Can update/modify company settings.'),)},
        ),
    ]
