# Generated by Django 5.0.2 on 2024-04-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='header_logo',
            field=models.ImageField(default='defaults/default_header.png', upload_to='company'),
        ),
    ]
