# Generated by Django 5.0.2 on 2024-04-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_config_page_content_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='page_content_number',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
