# Generated by Django 5.0.2 on 2024-05-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_config_page_content_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='page_content_number',
            field=models.PositiveIntegerField(),
        ),
    ]
