# Generated by Django 5.0.2 on 2024-02-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
