# Generated by Django 5.0.2 on 2024-02-14 15:26

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_userprofile_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatars/default.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='avatars'),
        ),
    ]
