# Generated by Django 5.0.2 on 2024-02-17 13:44

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatars/default.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='avatars'),
        ),
    ]
