# Generated by Django 5.0.2 on 2024-02-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_alter_userprofile_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='warehouse',
        ),
    ]
